### ISSUE TITLE
error divide by zero with some background image

### ISSUE THREAD

**Issue by martialowt** [SumiMakito/AwesomeQRCode#20] opened 2017-08-24 14:06 UTC
Hi,

with some drawable as background image, i have an error **divide by zero** : 
``System.err: java.lang.ArithmeticException: divide by zero
System.err:     at com.github.sumimakito.awesomeqr.AwesomeQRCode.getDominantColor(AwesomeQRCode.java:377)
System.err:     at com.github.sumimakito.awesomeqr.AwesomeQRCode.render(AwesomeQRCode.java:116)
System.err:     at com.github.sumimakito.awesomeqr.AwesomeQRCode.create(AwesomeQRCode.java:92)
System.err:     at com.github.sumimakito.awesomeqr.AwesomeQRCode.access$700(AwesomeQRCode.java:22)
System.err:     at com.github.sumimakito.awesomeqr.AwesomeQRCode$Renderer$1.run(AwesomeQRCode.java:526)``

**Comment by SumiMakito** [comment] 2017-08-25 16:11
I think the issue may be caused by a background image with no pixels satisfying the statement `r<200 && g<200 && b<200`, which is used for computing the dominant color without involving too much "light" colors since the foreground and background color of a QR code should not be quite similar. 

Anyway, the issue was fixed in commit cef384468a7fc0c075c2ef748252f86f03041e70.

Cheers 🍻

**Closed by SumiMakito** 2017-08-25 16:11 UTC
